// src/components/ArticleCard.vue
<script setup>
import { RouterLink } from 'vue-router'
import CoverImage from './CoverImage.vue'
import TagPill from './TagPill.vue'
import { formatCount, relativeTime } from '@/utils/format'

/**
 * 文章卡片。
 * props 传整个文章对象而不是拆成零散字段：列表页和首页共用这一个组件，
 * 拆散了以后每加一个展示字段就要同时改两处调用方。
 */
const props = defineProps({
  article: { type: Object, required: true },
  /** wide 用在首页精选位 */
  variant: { type: String, default: 'default' },
})

const detailRoute = computed(() => ({
  name: 'ArticleDetail',
  params: { slug: props.article.slug },
}))
import { computed } from 'vue'
</script>

<template>
  <article class="card" :class="{ 'card--wide': variant === 'wide' }">
    <RouterLink class="card__cover" :to="detailRoute" tabindex="-1">
      <CoverImage :path="article.cover_path" :seed="article.slug" :alt="article.title" />
    </RouterLink>
    <div class="card__body">
      <div class="card__tags">
        <TagPill v-for="tag in article.tags || []" :key="tag" :slug="tag" size="sm" />
      </div>
      <h3 class="card__title">
        <RouterLink :to="detailRoute">{{ article.title }}</RouterLink>
      </h3>
      <p v-if="article.summary" class="card__summary">{{ article.summary }}</p>
      <div class="card__meta">
        <span class="card__meta-item" :title="article.published_at || article.created_at">
          <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true">
            <rect x="3.5" y="5" width="17" height="15.5" rx="2.5" />
            <path d="M8 3v4M16 3v4M3.5 10h17" />
          </svg>
          {{ relativeTime(article.published_at || article.created_at) }}
        </span>
        <span class="card__meta-item">
          <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true">
            <circle cx="12" cy="12" r="8.5" />
            <path d="M12 8v4.4l3 1.8" />
          </svg>
          {{ article.reading_minutes || 1 }} 分钟
        </span>
        <span class="card__meta-item">
          <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <path d="M2.5 12s3.6-6.5 9.5-6.5S21.5 12 21.5 12s-3.6 6.5-9.5 6.5S2.5 12 2.5 12z" />
            <circle cx="12" cy="12" r="2.6" />
          </svg>
          {{ formatCount(article.views) }}
        </span>
      </div>
    </div>
  </article>
</template>

// src/components/ArticleCard.tsx
import { Link } from 'react-router-dom'
import type { Article } from '../lib/types'
import { useObjectUrl } from '../lib/hooks'
import { cn, coverGradient, formatCount, formatDateShort, relativeTime } from '../lib/utils'
import { IconClock, IconEye } from './icons'
import { TagPill } from './ui'

/** 封面：存的是对象键，展示时才换签名地址；拿不到就退化成渐变色块 */
export function CoverImage({
  path,
  seed,
  alt,
  className,
}: {
  path?: string | null
  seed: string
  alt: string
  className?: string
}) {
  const url = useObjectUrl(path)
  const gradient = coverGradient(seed)

  if (url) {
    return <img className={cn('cover-img', className)} src={url} alt={alt} loading="lazy" />
  }

  const glyph = alt.trim().slice(0, 1) || '#'
  return (
    <div className={cn('cover-fallback', className)} style={{ backgroundImage: gradient }} aria-hidden="true">
      <span className="cover-fallback__glyph">{glyph}</span>
      <span className="cover-fallback__grid" />
    </div>
  )
}

export function ArticleCard({ article, variant = 'default' }: { article: Article; variant?: 'default' | 'wide' }) {
  return (
    <article className={cn('card', variant === 'wide' && 'card--wide')}>
      <Link className="card__cover" to={`/article/${encodeURIComponent(article.slug)}`} tabIndex={-1}>
        <CoverImage path={article.cover_path} seed={article.slug} alt={article.title} />
      </Link>

      <div className="card__body">
        <div className="card__tags">
          {(article.tags ?? []).slice(0, 3).map((t) => (
            <TagPill key={t} slug={t} size="sm" />
          ))}
        </div>

        <h3 className="card__title">
          <Link to={`/article/${encodeURIComponent(article.slug)}`}>{article.title}</Link>
        </h3>

        {article.summary ? <p className="card__summary">{article.summary}</p> : null}

        <div className="card__meta">
          <span className="card__meta-item" title={article.published_at ?? article.created_at}>
            {formatDateShort(article.published_at ?? article.created_at)}
          </span>
          <span className="card__meta-item">
            <IconClock width={13} height={13} />
            {article.reading_minutes} 分钟
          </span>
          <span className="card__meta-item">
            <IconEye width={13} height={13} />
            {formatCount(article.views)}
          </span>
        </div>
      </div>
    </article>
  )
}

/** 工作台用的紧凑行式条目 */
export function ArticleRow({
  article,
  onDelete,
}: {
  article: Article
  onDelete?: (a: Article) => void
}) {
  return (
    <div className="row-item">
      <div className="row-item__thumb">
        <CoverImage path={article.cover_path} seed={article.slug} alt={article.title} />
      </div>
      <div className="row-item__main">
        <div className="row-item__top">
          <Link className="row-item__title" to={`/article/${encodeURIComponent(article.slug)}`}>
            {article.title}
          </Link>
          <span className={cn('badge', article.status === 'published' ? 'badge--ok' : 'badge--draft')}>
            {article.status === 'published' ? '已发布' : '草稿'}
          </span>
          {article.featured ? <span className="badge badge--star">精选</span> : null}
        </div>
        <div className="row-item__meta">
          <span>{relativeTime(article.updated_at)} 更新</span>
          <span>·</span>
          <span>{formatCount(article.views)} 阅读</span>
          <span>·</span>
          <span>{(article.tags ?? []).join(' / ') || '无标签'}</span>
        </div>
      </div>
      <div className="row-item__actions">
        <Link className="btn btn--sm btn--ghost" to={`/write/${article.id}`}>
          编辑
        </Link>
        <Link
          className="btn btn--sm btn--ghost"
          to={`/article/${encodeURIComponent(article.slug)}`}
        >
          查看
        </Link>
        {onDelete ? (
          <button type="button" className="btn btn--sm btn--danger-ghost" onClick={() => onDelete(article)}>
            删除
          </button>
        ) : null}
      </div>
    </div>
  )
}
