// src/pages/Account.tsx
import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { changePassword, useAuth } from '../lib/auth'
import { fetchMyArticles } from '../lib/api'
import { useDocumentTitle, useSiteSettings } from '../lib/hooks'
import { formatCount, formatDate } from '../lib/utils'
import { RequireAuth } from '../components/RequireAuth'
import { Field, Notice, PageLoading, Spinner } from '../components/ui'
import { IconLogout, IconSettings, IconUser } from '../components/icons'

function AccountInner() {
  const { user, uid, signOut } = useAuth()
  const { site } = useSiteSettings()
  const [oldPassword, setOldPassword] = useState('')
  const [newPassword, setNewPassword] = useState('')
  const [confirm, setConfirm] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [ok, setOk] = useState<string | null>(null)
  const [counts, setCounts] = useState<{ total: number; views: number } | null>(null)

  useDocumentTitle(`账号 · ${site.site_name}`)

  useEffect(() => {
    if (!uid) return
    fetchMyArticles(uid)
      .then((rows) =>
        setCounts({
          total: rows.length,
          views: rows.reduce((s, a) => s + (a.views ?? 0), 0),
        }),
      )
      .catch(() => setCounts(null))
  }, [uid])

  const submit = useCallback(
    async (e: React.FormEvent) => {
      e.preventDefault()
      setError(null)
      setOk(null)
      if (!oldPassword) return setError('请输入当前密码')
      if (newPassword.length < 8) return setError('新密码至少 8 位')
      if (newPassword !== confirm) return setError('两次输入的新密码不一致')
      if (newPassword === oldPassword) return setError('新密码不能与当前密码相同')

      setBusy(true)
      const res = await changePassword(oldPassword, newPassword)
      setBusy(false)
      if (!res.ok) {
        setError(res.message)
        return
      }
      setOldPassword('')
      setNewPassword('')
      setConfirm('')
      setOk('密码已更新。其它设备上的会话不会自动失效，如需强制下线可在数据库侧清理会话。')
    },
    [oldPassword, newPassword, confirm],
  )

  return (
    <div className="container section account-page">
      <header className="page-head">
        <h1 className="page-head__title">
          <IconUser width={20} height={20} />
          账号
        </h1>
        <p className="page-head__sub">登录身份由云端认证服务签发，前端只持有短期访问令牌。</p>
      </header>

      <div className="account-grid">
        <section className="side-panel">
          <h3 className="side-panel__title">
            <IconUser width={15} height={15} />
            当前身份
          </h3>
          <dl className="kv">
            <div>
              <dt>昵称</dt>
              <dd>{user?.nickname || '—'}</dd>
            </div>
            <div>
              <dt>邮箱</dt>
              <dd>{user?.email || '—'}</dd>
            </div>
            <div>
              <dt>用户 ID</dt>
              <dd>
                <code>{uid}</code>
              </dd>
            </div>
            <div>
              <dt>我的文章</dt>
              <dd>{counts ? `${counts.total} 篇` : '…'}</dd>
            </div>
            <div>
              <dt>累计阅读</dt>
              <dd>{counts ? formatCount(counts.views) : '…'}</dd>
            </div>
          </dl>
          <div className="panel-form__actions">
            <Link className="btn btn--ghost" to="/dashboard">
              <IconSettings width={15} height={15} />
              去工作台
            </Link>
            <button type="button" className="btn btn--danger-ghost" onClick={() => void signOut()}>
              <IconLogout width={15} height={15} />
              退出登录
            </button>
          </div>
        </section>

        <section className="side-panel">
          <h3 className="side-panel__title">修改密码</h3>
          <form className="panel-form" onSubmit={submit}>
            {error ? <Notice tone="error">{error}</Notice> : null}
            {ok ? <Notice tone="ok">{ok}</Notice> : null}
            <Field label="当前密码" required>
              <input
                type="password"
                autoComplete="current-password"
                value={oldPassword}
                onChange={(e) => setOldPassword(e.target.value)}
                placeholder="••••••••"
              />
            </Field>
            <Field label="新密码" required hint="至少 8 位">
              <input
                type="password"
                autoComplete="new-password"
                value={newPassword}
                onChange={(e) => setNewPassword(e.target.value)}
                placeholder="••••••••"
              />
            </Field>
            <Field label="确认新密码" required>
              <input
                type="password"
                autoComplete="new-password"
                value={confirm}
                onChange={(e) => setConfirm(e.target.value)}
                placeholder="••••••••"
              />
            </Field>
            <button type="submit" className="btn btn--primary" disabled={busy}>
              {busy ? <Spinner /> : null}
              更新密码
            </button>
            <p className="field__hint">
              忘记当前密码时，可以在<Link to="/login">登录页</Link>走「忘记密码」流程，用邮箱验证码重置。
            </p>
          </form>
        </section>
      </div>
    </div>
  )
}

export function AccountPage() {
  return (
    <RequireAuth>
      <AccountInner />
    </RequireAuth>
  )
}

// src/views/admin/Account.vue
<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { RouterLink } from 'vue-router'
import { message } from 'ant-design-vue'
import { changePassword, fetchMe } from '@/api/auth'
import { useUserStore } from '@/store/user'
import { useSiteSettings } from '@/composables/useSiteSettings'
import { useDocumentTitle } from '@/composables/useDocumentTitle'
import { formatDate } from '@/utils/format'

const { site } = useSiteSettings()
const store = useUserStore()
useDocumentTitle(computed(() => `账号 · ${site.value.site_name}`))

const user = computed(() => store.state.user)
const form = reactive({ oldPassword: '', newPassword: '', confirm: '' })
const busy = ref(false)

/** 后端只在登录后才知道用户详情，进来刷新一次，注册后立刻进来的也能拿到完整资料 */
onMounted(async () => {
  try {
    store.state.user = await fetchMe()
  } catch {
    /* 拦截器已经处理过 401，这里不用再报错 */
  }
})

const submit = async () => {
  if (form.newPassword !== form.confirm) {
    message.error('两次输入的新密码不一致')
    return
  }
  busy.value = true
  try {
    await changePassword({ oldPassword: form.oldPassword, newPassword: form.newPassword })
    message.success('密码已更新，下次登录请使用新密码')
    Object.assign(form, { oldPassword: '', newPassword: '', confirm: '' })
  } catch (e) {
    message.error(e?.message || '修改失败')
  } finally {
    busy.value = false
  }
}
</script>

<template>
  <div class="container section">
    <header class="page-head">
      <h1 class="page-head__title">账号</h1>
      <p class="page-head__sub">当前登录信息与密码修改</p>
    </header>

    <div class="account-grid">
      <div class="side-card">
        <h3 class="side-card__title">当前账号</h3>
        <div class="article__author" style="margin: 0">
          <div class="article__author-avatar">
            {{ (user?.nickname || user?.email || 'U').slice(0, 1).toUpperCase() }}
          </div>
          <div>
            <div class="article__author-name">{{ user?.nickname || '—' }}</div>
            <div class="article__author-bio">{{ user?.email }}</div>
          </div>
        </div>
        <div class="side-card__facts">
          <div class="kv"><span>角色</span><strong>{{ user?.role || 'AUTHOR' }}</strong></div>
          <div class="kv"><span>注册时间</span><strong>{{ formatDate(user?.created_at) || '—' }}</strong></div>
        </div>
        <RouterLink class="btn btn--ghost btn--sm" :to="{ name: 'Dashboard' }">回工作台</RouterLink>
      </div>

      <div class="panel-form">
        <h3 class="dashboard-section__title">修改密码</h3>
        <form class="form-grid" @submit.prevent="submit">
          <div class="field">
            <label class="field__label">当前密码 <span class="field__req">*</span></label>
            <input
              v-model="form.oldPassword"
              class="login-form__row"
              type="password"
              autocomplete="current-password"
              placeholder="现在使用的密码"
              required
            />
          </div>
          <div class="field">
            <label class="field__label">新密码 <span class="field__req">*</span></label>
            <input
              v-model="form.newPassword"
              class="login-form__row"
              type="password"
              autocomplete="new-password"
              placeholder="至少 8 位，最多 72 位"
              minlength="8"
              maxlength="72"
              required
            />
            <span class="field__hint">上限 72 位来自 BCrypt 的算法限制，更长的部分会被静默截断。</span>
          </div>
          <div class="field">
            <label class="field__label">确认新密码 <span class="field__req">*</span></label>
            <input
              v-model="form.confirm"
              class="login-form__row"
              type="password"
              autocomplete="new-password"
              placeholder="再输一次"
              required
            />
          </div>
          <div class="panel-form__actions">
            <a-button type="primary" html-type="submit" :loading="busy">更新密码</a-button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>
